version: '3.8'

services:
  node-app:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    network_mode: host
    command: sh -c "npm install && node server.js"
